### ISSUE TITLE
Implement Bootstrap

### ISSUE THREAD

**Issue by viniciusmeneses** [vini23hot/simple-gulp-boilerplate#2]
Import **Bootstrap** files in the `vendor` folders to the Gulp tasks automatically minify **Bootstrap** and include it in `dist` folder to can be used.

_It can be done installing Bootstrap node module and importing the files too._

**Comment by r10a** [comment]
Hey @vini23hot, Can I take up this issue?

**Comment by viniciusmeneses** [comment]
Yes!

**Comment by r10a** [comment]
Hey. Just a quick question. Do you want me to include the bootstrap dependency in package.json? Because I see that you haven't included any existing dependencies (jQuery, Normalize, etc) in there.

**Comment by ani4aniket** [comment]
I have some PRs . Is it correct?
