### ISSUE TITLE
Implement a HTML linter

### ISSUE THREAD

**Issue by viniciusmeneses** [vini23hot/simple-gulp-boilerplate#3]
Add a **HTML linter** in Gulp task to validate all HTML files and prevent problems.
Plugin to be used: [gulp-htmlhint](https://github.com/bezoerb/gulp-htmlhint)

_If an error is encountered, the task have to be stopped and it's needed to show in console the errors._

**Comment by r10a** [comment]
Hey @vini23hot. I have sent a pull request. Can you please review it?

**Comment by viniciusmeneses** [comment]
@slntRohit I'll review it after you commit the changes in PR #6
