### ISSUE TITLE
Implement a JS linter

### ISSUE THREAD

**Issue by viniciusmeneses** [vini23hot/simple-gulp-boilerplate#4]
Add a JS linter in Gulp task.
**See issue #3** 

Plugin to be used: [gulp-jshint](https://github.com/spalger/gulp-jshint), [gulp-eslint](https://github.com/adametry/gulp-eslint) or any other.

**Comment by r10a** [comment]
Hey @vini23hot . I have sent a pull request. Can you please review it?
